//! Fixtures generated by the original Fortran executable, never the Rust port.
use oneloop::OneLoopExpressions;
use symbolica::prelude::RealLike;
use symbolica::{
    domains::{
        float::{Complex, Float},
        rational::Rational,
    },
    parse,
};

#[test]
fn fortran_fixtures() {
    // Start the whole Symbolica workload here, before this thread acquires a
    // restricted-license permit. The caller never needs RUST_MIN_STACK.
    std::thread::Builder::new()
        .stack_size(128 * 1024 * 1024)
        .spawn(|| check_fixtures(include_str!("data/parity.txt"), true))
        .unwrap()
        .join()
        .unwrap();
}

/// Exploratory audit input is separate from the mandatory acceptance inventory.
/// Usage: ONELOOP_AUDIT_FIXTURES=/path/table.txt cargo test --test parity
/// audit_extra_fortran_fixtures -- --ignored --test-threads=1 --nocapture
#[test]
#[ignore = "requires an explicitly supplied exploratory Fortran fixture table"]
fn audit_extra_fortran_fixtures() {
    let path = std::env::var("ONELOOP_AUDIT_FIXTURES").expect("set ONELOOP_AUDIT_FIXTURES");
    let fixtures = std::fs::read_to_string(path).expect("read audit fixture table");
    std::thread::Builder::new()
        .stack_size(128 * 1024 * 1024)
        .spawn(move || check_fixtures(&fixtures, false))
        .unwrap()
        .join()
        .unwrap();
}

fn check_fixtures(fixtures: &str, enforce_inventory: bool) {
    let ctx = OneLoopExpressions::new();
    let ap = [parse!("oracle_a_mass"), parse!("oracle_a_mu")];
    let mut ae = ctx
        .evaluator(oneloop::a0(&ap[0], &ap[1]).coefficients(), &ap)
        .unwrap()
        .map_coeff(&|x: &Complex<Rational>| Complex::new(x.re.to_f64(), x.im.to_f64()));
    let bp = [
        parse!("oracle_b_p"),
        parse!("oracle_b_m0"),
        parse!("oracle_b_m1"),
        parse!("oracle_b_mu"),
    ];
    let mut be = ctx
        .evaluator(
            oneloop::b0(&bp[0], &bp[1], &bp[2], &bp[3]).coefficients(),
            &bp,
        )
        .unwrap()
        .map_coeff(&|x: &Complex<Rational>| Complex::new(x.re.to_f64(), x.im.to_f64()));
    let mut dbe = ctx
        .evaluator(
            oneloop::db0(&bp[0], &bp[1], &bp[2], &bp[3]).coefficients(),
            &bp,
        )
        .unwrap()
        .map_coeff(&|x: &Complex<Rational>| Complex::new(x.re.to_f64(), x.im.to_f64()));
    let cp = [
        parse!("p1"),
        parse!("p2"),
        parse!("p3"),
        parse!("m1"),
        parse!("m2"),
        parse!("m3"),
        parse!("mu"),
    ];
    let cs = ctx.c0([&cp[0], &cp[1], &cp[2]], [&cp[3], &cp[4], &cp[5]], &cp[6]);
    let cexact = ctx.evaluator(cs.coefficients(), &cp).unwrap();
    let mut ce = cexact
        .clone()
        .map_coeff(&|x: &Complex<Rational>| Complex::new(x.re.to_f64(), x.im.to_f64()));
    let dp = [
        parse!("p1"),
        parse!("p2"),
        parse!("p3"),
        parse!("p4"),
        parse!("p12"),
        parse!("p23"),
        parse!("m1"),
        parse!("m2"),
        parse!("m3"),
        parse!("m4"),
        parse!("mu"),
    ];
    let ds = ctx.d0(
        [&dp[0], &dp[1], &dp[2], &dp[3], &dp[4], &dp[5]],
        [&dp[6], &dp[7], &dp[8], &dp[9]],
        &dp[10],
    );
    let mut de = ctx
        .evaluator(ds.coefficients(), &dp)
        .unwrap()
        .map_coeff(&|x: &Complex<Rational>| Complex::new(x.re.to_f64(), x.im.to_f64()));
    let mut failures = Vec::new();
    let mut count = 0;
    let mut family_counts = [0; 5]; // A0, B0, dB0, C0, D0.
    let mut mass_masks = [0_u32; 5];
    let mut pole_cases = [0; 5];
    for (line_number, line) in fixtures.lines().enumerate() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let values = line
            .split_whitespace()
            .map(|s| s.parse::<f64>().unwrap())
            .collect::<Vec<_>>();
        assert!(!values.is_empty(), "empty fixture row {}", line_number + 1);
        assert!(
            values.iter().all(|x| x.is_finite()),
            "nonfinite fixture row {}",
            line_number + 1
        );
        let (family, legs, np, scale_power) = match values[0] {
            1. => (0, 1, 0, -1),
            2. => (1, 2, 1, 0),
            -2. => (2, 2, 1, 1),
            3. => (3, 3, 3, 1),
            4. => (4, 4, 6, 2),
            other => panic!("invalid integral kind {other} on row {}", line_number + 1),
        };
        assert_eq!(
            values.len(),
            2 + np + 2 * legs + 6,
            "invalid fixture shape on row {}",
            line_number + 1
        );
        assert!(
            values[1] > 0.,
            "nonpositive scale on row {}",
            line_number + 1
        );
        family_counts[family] += 1;
        if !enforce_inventory && family_counts.iter().sum::<usize>() % 25 == 0 {
            eprintln!(
                "Audit progress: {} points; {} mismatches so far",
                family_counts.iter().sum::<usize>(),
                failures.len()
            );
        }
        let mask = values[2 + np..2 + np + 2 * legs]
            .chunks_exact(2)
            .enumerate()
            .fold(0, |mask, (i, m)| {
                mask | (usize::from(m[0] != 0. || m[1] != 0.) << i)
            });
        mass_masks[family] |= 1 << mask;
        let mut input = values[2..2 + np]
            .iter()
            .map(|&x| Complex::new(x, 0.))
            .collect::<Vec<_>>();
        input.extend(
            values[2 + np..2 + np + 2 * legs]
                .chunks_exact(2)
                .map(|v| Complex::new(v[0], v[1])),
        );
        input.push(Complex::new(values[1], 0.));
        let expected = &values[2 + np + 2 * legs..];
        assert_eq!(expected.len(), 6);
        if expected[2..].iter().any(|&x| x != 0.) {
            pole_cases[family] += 1;
        }
        let mut out = [Complex::new(0., 0.); 3];
        match family {
            0 => ae.evaluate(&input, &mut out),
            1 => be.evaluate(&input, &mut out),
            2 => dbe.evaluate(&input, &mut out),
            3 => ce.evaluate(&input, &mut out),
            4 => de.evaluate(&input, &mut out),
            _ => unreachable!(),
        }
        // Normalize the mass dimension before applying an absolute tolerance:
        // A0 scales as mu², B0 is dimensionless, dB0/C0 as 1/mu², D0 as 1/mu⁴.
        let characteristic_scale = if enforce_inventory {
            values[1]
        } else {
            // Exploratory scans vary mu independently of fixed kinematics.
            // Normalize by kinematics so small mu cannot loosen their checks.
            let scale = values[2..2 + np + 2 * legs]
                .iter()
                .fold(0_f64, |scale, value| scale.max(value.abs()));
            if scale == 0. { 1. } else { scale }
        };
        let normalization = characteristic_scale.powi(scale_power);
        assert!(normalization.is_finite() && normalization > 0.);
        for (k, (actual, reference)) in out.into_iter().zip(expected.chunks_exact(2)).enumerate() {
            let error = (actual.re - reference[0]).hypot(actual.im - reference[1]) * normalization;
            let tolerance = 2e-10 + 2e-8 * reference[0].hypot(reference[1]) * normalization;
            if !actual.re.is_finite()
                || !actual.im.is_finite()
                || !error.is_finite()
                || error > tolerance
            {
                failures.push(format!("line={} kind={} coefficient={k} actual={actual:?} expected={reference:?} normalized_error={error:e}",line_number+1,values[0]));
            }
            count += 1;
        }
    }
    assert!(count > 0, "empty fixture table");
    if enforce_inventory {
        assert_eq!(
            family_counts,
            [4, 13, 12, 125, 139],
            "fixture inventory changed"
        );
        assert_eq!(count, 879, "truncated coefficient fixture table");
        assert_eq!(mass_masks[3], 0xff, "missing triangle mass mask");
        assert_eq!(mass_masks[4], 0xffff, "missing box mass mask");
        assert!(
            pole_cases.iter().all(|&n| n > 0),
            "missing nonzero pole coverage: {pole_cases:?}"
        );
    }
    eprintln!("Family points [A0,B0,dB0,C0,D0]: {family_counts:?}; with poles: {pole_cases:?}");
    eprintln!(
        "Checked {count} Fortran coefficients; {} failures",
        failures.len()
    );
    assert!(failures.is_empty(), "{}", failures.join("\n"));
    let mut previous: Option<Complex<Float>> = None;
    for bits in [128, 256] {
        let mut eval = cexact.clone().map_coeff_with_prec(
            &|x| {
                Complex::new(
                    x.re.to_multi_prec_float(bits),
                    x.im.to_multi_prec_float(bits),
                )
            },
            bits,
        );
        let input = [(1, 1), (2, 1), (3, 1), (1, 2), (7, 10), (7, 5), (1, 1)]
            .map(|(n, d)| Complex::new(Float::with_val(bits, n) / d, Float::new(bits)));
        let mut output =
            core::array::from_fn::<_, 3, _>(|_| Complex::new(Float::new(bits), Float::new(bits)));
        eval.evaluate(&input, &mut output);
        let value = output[0].clone();
        assert!((value.re.to_f64() + 1.760932031767186).abs() < 1e-12);
        assert!(value.im.to_f64().abs() < 1e-28);
        if let Some(old) = previous {
            assert!((value.clone() - old).re.to_f64().abs() < 1e-28);
        }
        previous = Some(value);
    }
}
