// Generated by examples/generate_native.rs from repaired exact expressions.
// Regenerate; do not hand-edit. No bytecode, numerical regulator, or Fortran callback.
#![allow(unused_imports, unused_variables)]
use super::{C, Context, NativeFloat};
use super::primitives::*;

pub(super) fn evaluate<T: NativeFloat>(input: &[C<T>], ctx: &Context<T>) -> [C<T>; 3] {
    let a0 = &input[0];
    let a1 = &input[1];
    let v0 = helper_0(a0, a1, ctx.constant(0), ctx.constant(1), ctx.constant(2), ctx.constant(3), ctx.constant(4), ctx);
    let v1 = helper_1(a0, a1, ctx);
    let v2 = helper_2(a0, a1, ctx.constant(2), ctx);
    [(*(&v0)).clone(), (*(&v1)).clone(), (*(&v2)).clone()]
}

fn helper_0<T: NativeFloat>(a0: &C<T>, a1: &C<T>, a2: &C<T>, a3: &C<T>, a4: &C<T>, a5: &C<T>, a6: &C<T>, ctx: &Context<T>) -> C<T> {
    let v23 = if truth(a0) {
        let v0 = powi(a1, -1, false);
        let v1 = mul(a0, &v0);
        let v2 = if truth(&v1) {
            (*(&v1)).clone()
        } else {
            (*(a4)).clone()
        };
        let v4 = conj(&v2);
        let v5 = mul(a3, &v4);
        let v6 = add(&v2, &v5);
        let v19 = if truth(&v6) {
            let v8 = log(&v2);
            (*(&v8)).clone()
        } else {
            let v10 = abs(&v2);
            let v11 = log(&v10);
            let v13 = mul(a3, &v10);
            let v14 = add(&v2, &v13);
            let v15 = if truth(&v14) {
                (*(a2)).clone()
            } else {
                (*(a4)).clone()
            };
            let v16 = mul(a5, a6);
            let v17 = mul(&v16, &v15);
            let v18 = add(&v11, &v17);
            (*(&v18)).clone()
        };
        let v20 = mul(a3, &v19);
        let v21 = add(a2, &v20);
        let v22 = mul(a0, &v21);
        (*(&v22)).clone()
    } else {
        (*(a4)).clone()
    };
    (*(&v23)).clone()
}

fn helper_1<T: NativeFloat>(a0: &C<T>, a1: &C<T>, ctx: &Context<T>) -> C<T> {
    (*(a0)).clone()
}

fn helper_2<T: NativeFloat>(a0: &C<T>, a1: &C<T>, a2: &C<T>, ctx: &Context<T>) -> C<T> {
    (*(a2)).clone()
}

