[package]
name = "oneloop-symbolica-audit"
version = "0.0.0"
edition = "2024"
publish = false
[features]
default = ["bincode", "native_code_generation"]
bincode = []
native_code_generation = []
[dependencies]
symbolica = { version = "3.0", default-features = false, features = ["tracing_max_level_info", "integer-gmp", "float-mpfr", "native_code_generation", "bincode"] }
bincode = "2.0"
wide = "1"
[patch.crates-io]
symbolica = { git = "https://github.com/symbolica-dev/symbolica", rev = "a19c760dd567c239f30d87e4e924ca2f8b8457ab" }
numerica = { git = "https://github.com/symbolica-dev/symbolica", rev = "a19c760dd567c239f30d87e4e924ca2f8b8457ab" }

[workspace]
